# This file is used to ensure that the Prod container boots without any issues.
services:
  app:
    container_name: kite_app
    env_file: .env.development
    build:
      context: .
      dockerfile: deployments/openshift/Containerfile.production
    ports:
      - "8080:8080"
    volumes:
      - ./configs/kube-config.yaml:/app/configs/kube-config.yaml:ro
      # Exclude build artifacts
      - /opt/app-root/src/tmp
      - /opt/app-root/src/vendor
    depends_on:
      db:
        # Ensure the DB is ready before the app
        condition: service_healthy
      migrator:
        # Ensure migrator has ran
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080/api/v1/health/"]
      interval: 19s
      timeout: 9s
      retries: 4
      start_period: 30s

  migrator:
    container_name: kite_migrator
    env_file: .env.development
    build:
      context: .
      dockerfile: deployments/openshift/Containerfile.init
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: kite_db
    image: registry.redhat.io/rhel9/postgresql-15
    environment:
      POSTGRESQL_USER: kite
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: issuesdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kite -d issuesdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
