---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: simple-pipeline
  namespace: tekton-pipelines
spec:
  tasks:
  - name: echo-task
    taskSpec:
      stepTemplate:
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          runAsUser: 1000
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
      steps:
      - name: echo-message
        image: busybox:1.36
        script: |
          #!/bin/sh
          echo "Hello, Tekton!"
          exit 0
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: simple-pipeline-run
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: simple-pipeline
